### ISSUE TITLE
`:NnnExplorer` bugs and additional features

### ISSUE THREAD

**Issue by mcchrish** [mcchrish/nnn.vim#128]
- [x] `:NnnExplorer` should toggle the nnn window instead of opening a new window. #138
- [x] Each tab should only have one explorer window. #138
- [ ] Nice to have: option to have the same nnn buffer in all tabs.
- [x] Nice to have: option to change window background when not in focus. Sometimes it's hard to tell where the focus is. #135 
- [ ] Set only `bufhidden=wipe` to `buflisted` to nnn picker buffer. Might be useful to still list the explorer buffer specially for navigation.

**Comment by mcchrish** [comment]
@N-R-K the code looks fine.
I'm not sure I'd want this behavior though. But if some wants it, maybe a have a config to turn it on.

**Comment by N-R-K** [comment]
@mcchrish I'm thinking about adding it to the docs similar to NERDTree.

**Comment by N-R-K** [comment]
> * [ ]  `:NnnExplorer` should toggle the nnn window instead of opening a new window.

Any plans on how to implement this? I was trying out something like this, but this doesn't work well when called form a different tab.

```diff
diff --git a/autoload/nnn.vim b/autoload/nnn.vim
index a4929da..70844aa 100644
--- a/autoload/nnn.vim
+++ b/autoload/nnn.vim
@@ -3,6 +3,7 @@ let s:action = ''
 let s:nnn_conf_dir = (!empty($XDG_CONFIG_HOME) ? $XDG_CONFIG_HOME : $HOME.'/.config') . '/nnn'
 " The fifo used by the persistent explorer
 let s:explorer_fifo = ""
+let s:explorer_winid = 0
 
 let s:local_ses = 'nnn_vim_'
 " Add timestamp for convenience
@@ -364,6 +365,11 @@ function! nnn#pick(...) abort
 endfunction
 
 function! nnn#explorer(...) abort
+    if s:explorer_winid > 0
+        call win_execute(s:explorer_winid, 'close!')
+        let s:explorer_winid = 0
+        return
+    endif
     let l:directory = get(a:, 1, '')
     let l:default_opts = { 'edit': 'edit' }
     let l:opts = extend(l:default_opts, get(a:, 2, {}))
@@ -388,6 +394,7 @@ function! nnn#explorer(...) abort
     call system('mkfifo '.shellescape(s:explorer_fifo))
     let l:opts.term = s:build_window(l:layout, { 'cmd': l:cmd, 'on_exit': l:On_exit })
     let b:tbuf = l:opts.term
+    let s:explorer_winid = l:opts.term.winhandle
 
     call s:explorer_job()
```

**Comment by mcchrish** [comment]
Maybe store in tab local variable instead of script?
```vim
let t:explorer_winid = 0
```

**Comment by N-R-K** [comment]
>   * [ ]  `:NnnExplorer` should toggle the nnn window instead of opening a new window.
>   * [ ]  Each tab should only have one explorer window.

#138 should take care of both of these.

**Comment by dave-kennedy** [comment]
This seems a good place to mention the mappings defined by `g:nnn#action` do not appear to work from the explorer view.
